apiVersion: v1
kind: Service
metadata:
  name: fruitvision-model-fastapi-service-${NAMESPACE}
  namespace: ${NAMESPACE}
  labels:
    app: fruitvision-app
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: fruitvision-app
  type: ClusterIP
  # type: NodePort